# Site settings
title: LUMI Talks
subtitle: by Xiaofeng QU
email: quxiaofeng@lumiunited.com
description: A responsive site template designed by HTML5 Up<br /> and released under the Creative Commons.
baseurl: "/lumitalks" # the subpath of your site, e.g. /blog
url: "http://www.quxiaofeng.me" # the base hostname & protocol for your site
author: Dr. Xiaofeng QU
street_address: 1 Tangling Road
city: Shenzhen
state: Guangdong
zip_code: 518052
country: "People's Republic of China"
phone: (86) 147-146-05326

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# Social settings
500px_url:
facebook_url: https://www.facebook.com/quxiaofeng
github_url: https://github.com/quxiaofeng
gitlab_url: 
googleplus_url: 
instagram_url: https://instagram.com/quxiaofeng
linkedin_url: https://www.linkedin.com/in/quxiaofeng
pinterest_url:
slack_url:
twitter_url: https://twitter.com/quxiaofeng

# Build settings
markdown: kramdown

sass:
  style: compressed
